# Node docker image on which this would be run


stages:
  - test_typescript
  - test_rust

# TypeScript
TestTypeScript:
  stage: test_typescript
  image:
    name: node:16-alpine
    entrypoint: [""]
  script:
    - cd ts
    - npm install -g typescript
    - tsc -p tsconfig.test.json
    - node js_test/test/matrix_test.js
    - node js_test/test/bspline_test.js
    - node js_test/test/nurbs_test.js
    - node js_test/test/lu_test.js
    - node js_test/test/linsystem_test.js
    - node js_test/test/quad_test.js

# Rust
TestRust:
  stage: test_rust
  image:
    name: rust:1.57-bullseye
    entrypoint: [""]
  script:
    - cd rust/isogeometric-analysis
    - cargo build
    - cargo test -- --test-threads=1