[package]
name = "isogeometric_analysis_benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies.isogeometric_analysis]
path = "../isogeometric-analysis"

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
gnuplot = "0.0.37"
structopt = "0.3.25"
flo_curves = "0.6.0"